### ISSUE TITLE
Pushing a Kotlin library does not work (Mixed aar/jar artifacts)

### ISSUE THREAD

**Issue by danielgindi** [Vorlonsoft/GradleMavenPush#1] opened 2018-07-27 05:12 UTC
The generated repo contains a `.jar` file, but `.aar.asc`. 
So it complains about a missing signature for the main artifact.

Is this a known issue with kotlin?

**Comment by AlexanderLS** [comment] 2018-07-27 13:26
Hi @danielgindi ,

I investigated this issue and couldn't reproduce it.

1. What Developer IDE did you use (Android Studio (3.3, 3.2, 3.1), Eclipse, IntelliJ IDEA, other)? Try to use Android Studio 3.3 Canary 3
2. Something wrong in your build.gradle files, can you send them? If it's Open Source project can I look at it?
3. Maybe it something like [android gradle plugin should not conflict w/ java gradle plugin](https://issuetracker.google.com/issues/36976519) issue. Google won't fix it.
4. I assigned developer for the small feature that can help you.

Thanks.

**Comment by danielgindi** [comment] 2018-07-27 14:06
Thanks for the quick response :-)
You can take a look here: https://github.com/danielgindi/android-helpers
It's a small "general utility" repo that I use in several projects to make life easier.

**Comment by AlexanderLS** [comment] 2018-07-31 17:47
Hi @danielgindi 

Issue confirmed. It's not Kotlin bug. It's Gradle/Other plugins bug. We'll find workaround for it for our plugin someday... :( 

You can add `POM_PACKAGING` (default is "aar" for Gradle Android Artifacts and "jar" for Gradle Java Artifacts and Gradle Kotlin Artifacts) and change it's value. Depends on Gradle/Plugins versions this option: 

1. Changes `<packaging>` tag in the generated pom file only; 
2. Changes main artifact file extension and `<packaging>` tag in the generated pom file; 
3. Changes main artifact and it's asc file extensions and changes `<packaging>` tag in the generated pom file.

**IMPORTANT!** In your project `POM_PACKAGING` doesn't generate JAR library, it only changes file extension of AAR library from aar to jar

We added 2 options for you and others:
- Add `ANDROID_JAR_ARTIFACT` (default is "false") and set it to "true" to generate Gradle Android Artifact jar. You'll get both `POM_PACKAGING` value (default is "aar" for Gradle Android Artifacts) and "jar" artifacts in your Android library project.
- Add `FATJAR_ARTIFACT` (default is "false") and set it to "true" to generate fatjar. You'll get both `POM_PACKAGING` value (default is "aar" for Gradle Android Artifacts and "jar" for Gradle Java Artifacts and Gradle Kotlin Artifacts) and "fatjar" artifacts.

I sent Pull Request to your library with updated properties - https://github.com/danielgindi/android-helpers/pull/1

Thanks

**Closed as completed by AlexanderLS** 2018-07-31 17:47 UTC
Labels: bug

**Comment by danielgindi** [comment] 2018-07-31 18:22
Thank you very much! You even surprised with a PR :-)

I tried now and it published successfully!
